import { watch, writeFileSync } from "node:fs"
import path from "node:path"
import Ajv from "ajv"
import { Glob } from "bun"
import manifestSchema from "custom-elements-manifest/schema.json" with { type: "json" }
import { componentMetadata } from "./component-metadata"

const DIR = path.join(process.cwd(), "src", "components")
const OUT = path.join(process.cwd(), "src", "globals.d.ts")
const PUBLIC_TYPES_OUT = path.join(process.cwd(), "src", "custom-elements.ts")
const MANIFEST_OUT = path.join(process.cwd(), "custom-elements.json")
const GLOB = path.join(DIR, "**", "*.{ts,tsx}")
const glob = new Glob(GLOB)
const validateManifest = new Ajv({ allErrors: true, strict: false }).compile(manifestSchema)

const kebabCase = (value: string) =>
	value
		.replace(/([a-z0-9])([A-Z])/g, "$1-$2")
		.replace(/[^a-zA-Z0-9]+/g, "-")
		.replace(/^-|-$/g, "")
		.toLowerCase()

const pascalCase = (value: string) =>
	value
		.split("-")
		.map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
		.join("")

const template = (
	data: {
		fileName: string
		typeName: string
		relPath: string
	}[],
) =>
	`// AUTOGENERATED - DO NOT EDIT
import type * as React from "react"
${data.map((d) => `import type { Type as ${d.typeName} } from "${d.relPath}"`).join("\n")}

declare global {
  interface HTMLElementTagNameMap {
${data.map((d) => `    "${d.fileName}": ${d.typeName}["Element"]`).join("\n")}
  }

}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
${data
	.map(
		(d) =>
			`      "${d.fileName}": React.DetailedHTMLProps<React.HTMLAttributes<${d.typeName}["Element"]>, ${d.typeName}["Element"]> & ${d.typeName}["Definition"]`,
	)
	.join("\n")}
    }
  }
}
`

const publicTypesTemplate = (
	data: {
		fileName: string
		typeName: string
		relPath: string
	}[],
) => `// AUTOGENERATED - DO NOT EDIT
${data.map((d) => `import type { Type as ${d.typeName} } from "${d.relPath}.js"`).join("\n")}

declare global {
  interface HTMLElementTagNameMap {
${data.map((d) => `    "${d.fileName}": ${d.typeName}["Element"]`).join("\n")}
  }
}
`

const makeFile = (files: string[]) => {
	const collisions: string[] = []
	const data = files.map((f) => {
		const name = kebabCase(path.basename(f).replace(path.extname(f), ""))

		if (collisions.includes(name)) {
			console.error(`[error] <${name} /> in ${f}`)
			throw new Error(`Duplicate components detected`)
		}

		collisions.push(name)

		return {
			fileName: name,
			typeName: `${pascalCase(name)}Type`,
			relPath: `./${path.relative(path.dirname(OUT), f.replace(path.extname(f), "")).replaceAll(path.sep, "/")}`,
		}
	})

	writeFileSync(OUT, template(data), { encoding: "utf-8" })
	writeFileSync(PUBLIC_TYPES_OUT, publicTypesTemplate(data), { encoding: "utf-8" })
	const manifest = {
		schemaVersion: "2.1.0",
		readme: "README.md",
		modules: data.map((item) => {
			const metadata = componentMetadata[item.fileName]
			const declarationName = item.typeName.replace(/Type$/, "")
			const members = metadata.members?.map(
				({ attributeName: _attributeName, ...member }) => member,
			)
			const attributes = metadata.members
				?.filter(({ attributeName }) => attributeName)
				.map(({ attributeName, name, type }) => ({
					fieldName: name,
					name: attributeName,
					type,
				}))

			return {
				kind: "javascript-module",
				path: `dist/components/${item.fileName}.js`,
				declarations: [
					{
						...metadata,
						attributes,
						customElement: true,
						kind: "class",
						members,
						name: declarationName,
						superclass: { name: "HTMLElement" },
						tagName: item.fileName,
					},
				],
				exports: [
					{
						declaration: { name: declarationName },
						kind: "custom-element-definition",
						name: item.fileName,
					},
				],
			}
		}),
	}

	if (!validateManifest(manifest)) {
		throw new Error(
			`Invalid Custom Elements Manifest:\n${JSON.stringify(validateManifest.errors, null, 2)}`,
		)
	}

	writeFileSync(MANIFEST_OUT, `${JSON.stringify(manifest, null, 2)}\n`, { encoding: "utf-8" })
}

const run = async () => {
	const fileList = []
	for await (const file of glob.scan(".")) {
		fileList.push(file)
	}

	makeFile(fileList.sort())
}

if (process.env.WATCH !== "false") {
	const watcher = watch(DIR, async (event, filename) => {
		if (process.env.DEBUG) console.log(`Detected ${event} in ${filename}`)
		await run()
	})

	process.on("SIGINT", () => {
		watcher?.close()

		process.exit(0)
	})
}

run()
