// AUTOGENERATED - DO NOT EDIT
import type { Type as HycnAccordionType } from "./components/hycn-accordion.js"
import type { Type as HycnAlertType } from "./components/hycn-alert.js"
import type { Type as HycnAvatarType } from "./components/hycn-avatar.js"
import type { Type as HycnBadgeType } from "./components/hycn-badge.js"
import type { Type as HycnBreadcrumbType } from "./components/hycn-breadcrumb.js"
import type { Type as HycnButtonType } from "./components/hycn-button.js"
import type { Type as HycnCardType } from "./components/hycn-card.js"
import type { Type as HycnCarouselType } from "./components/hycn-carousel.js"
import type { Type as HycnCheckboxType } from "./components/hycn-checkbox.js"
import type { Type as HycnComboboxType } from "./components/hycn-combobox.js"
import type { Type as HycnDatePickerType } from "./components/hycn-date-picker.js"
import type { Type as HycnDialogType } from "./components/hycn-dialog.js"
import type { Type as HycnDisclosureType } from "./components/hycn-disclosure.js"
import type { Type as HycnFileInputType } from "./components/hycn-file-input.js"
import type { Type as HycnFlexType } from "./components/hycn-flex.js"
import type { Type as HycnIconType } from "./components/hycn-icon.js"
import type { Type as HycnImageType } from "./components/hycn-image.js"
import type { Type as HycnListType } from "./components/hycn-list.js"
import type { Type as HycnMenuType } from "./components/hycn-menu.js"
import type { Type as HycnNumberInputType } from "./components/hycn-number-input.js"
import type { Type as HycnPopoverType } from "./components/hycn-popover.js"
import type { Type as HycnRadioGroupType } from "./components/hycn-radio-group.js"
import type { Type as HycnSelectType } from "./components/hycn-select.js"
import type { Type as HycnSkeletonType } from "./components/hycn-skeleton.js"
import type { Type as HycnSliderType } from "./components/hycn-slider.js"
import type { Type as HycnSwitchType } from "./components/hycn-switch.js"
import type { Type as HycnTableType } from "./components/hycn-table.js"
import type { Type as HycnTabsType } from "./components/hycn-tabs.js"
import type { Type as HycnTagType } from "./components/hycn-tag.js"
import type { Type as HycnTextInputType } from "./components/hycn-text-input.js"
import type { Type as HycnTextType } from "./components/hycn-text.js"
import type { Type as HycnToastType } from "./components/hycn-toast.js"
import type { Type as HycnTooltipType } from "./components/hycn-tooltip.js"
import type { Type as HycnTreeType } from "./components/hycn-tree.js"
import type { Type as HycnVisuallyHiddenType } from "./components/hycn-visually-hidden.js"
import type { Type as SimpleCounterType } from "./components/simple-counter.js"

declare global {
  interface HTMLElementTagNameMap {
    "hycn-accordion": HycnAccordionType["Element"]
    "hycn-alert": HycnAlertType["Element"]
    "hycn-avatar": HycnAvatarType["Element"]
    "hycn-badge": HycnBadgeType["Element"]
    "hycn-breadcrumb": HycnBreadcrumbType["Element"]
    "hycn-button": HycnButtonType["Element"]
    "hycn-card": HycnCardType["Element"]
    "hycn-carousel": HycnCarouselType["Element"]
    "hycn-checkbox": HycnCheckboxType["Element"]
    "hycn-combobox": HycnComboboxType["Element"]
    "hycn-date-picker": HycnDatePickerType["Element"]
    "hycn-dialog": HycnDialogType["Element"]
    "hycn-disclosure": HycnDisclosureType["Element"]
    "hycn-file-input": HycnFileInputType["Element"]
    "hycn-flex": HycnFlexType["Element"]
    "hycn-icon": HycnIconType["Element"]
    "hycn-image": HycnImageType["Element"]
    "hycn-list": HycnListType["Element"]
    "hycn-menu": HycnMenuType["Element"]
    "hycn-number-input": HycnNumberInputType["Element"]
    "hycn-popover": HycnPopoverType["Element"]
    "hycn-radio-group": HycnRadioGroupType["Element"]
    "hycn-select": HycnSelectType["Element"]
    "hycn-skeleton": HycnSkeletonType["Element"]
    "hycn-slider": HycnSliderType["Element"]
    "hycn-switch": HycnSwitchType["Element"]
    "hycn-table": HycnTableType["Element"]
    "hycn-tabs": HycnTabsType["Element"]
    "hycn-tag": HycnTagType["Element"]
    "hycn-text-input": HycnTextInputType["Element"]
    "hycn-text": HycnTextType["Element"]
    "hycn-toast": HycnToastType["Element"]
    "hycn-tooltip": HycnTooltipType["Element"]
    "hycn-tree": HycnTreeType["Element"]
    "hycn-visually-hidden": HycnVisuallyHiddenType["Element"]
    "simple-counter": SimpleCounterType["Element"]
  }
}
