// AUTOGENERATED - DO NOT EDIT
import type { Type as HycnComboboxType } from "./components/hycn-combobox.js"
import type { Type as HycnDialogType } from "./components/hycn-dialog.js"
import type { Type as HycnMenuType } from "./components/hycn-menu.js"
import type { Type as HycnTabsType } from "./components/hycn-tabs.js"
import type { Type as HycnTreeType } from "./components/hycn-tree.js"
import type { Type as HycnVisuallyHiddenType } from "./components/hycn-visually-hidden.js"
import type { Type as SimpleCounterType } from "./components/simple-counter.js"

declare global {
  interface HTMLElementTagNameMap {
    "hycn-combobox": HycnComboboxType["Element"]
    "hycn-dialog": HycnDialogType["Element"]
    "hycn-menu": HycnMenuType["Element"]
    "hycn-tabs": HycnTabsType["Element"]
    "hycn-tree": HycnTreeType["Element"]
    "hycn-visually-hidden": HycnVisuallyHiddenType["Element"]
    "simple-counter": SimpleCounterType["Element"]
  }
}

export {}
