// AUTOGENERATED - DO NOT EDIT
import { Type as HycnCloseButtonType } from "./components/hycn-close-button"
import { Type as HycnVisuallyHiddenType } from "./components/hycn-visually-hidden"
import { Type as SimpleCounterType } from "./components/simple-counter"
import { Type as HycnUnstyledButtonType } from "./components/hycn-unstyled-button"
import { Type as HycnButtonType } from "./components/hycn-button"
import { Type as HycnActionIconType } from "./components/hycn-action-icon"

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "hycn-close-button": HycnCloseButtonType["Definition"]
      "hycn-visually-hidden": HycnVisuallyHiddenType["Definition"]
      "simple-counter": SimpleCounterType["Definition"]
      "hycn-unstyled-button": HycnUnstyledButtonType["Definition"]
      "hycn-button": HycnButtonType["Definition"]
      "hycn-action-icon": HycnActionIconType["Definition"]
    }
  }
}
