// AUTOGENERATED - DO NOT EDIT
import type * as React from "react"
import type { Type as HycnAccordionType } from "./components/hycn-accordion"
import type { Type as HycnAlertType } from "./components/hycn-alert"
import type { Type as HycnAvatarType } from "./components/hycn-avatar"
import type { Type as HycnBadgeType } from "./components/hycn-badge"
import type { Type as HycnBreadcrumbType } from "./components/hycn-breadcrumb"
import type { Type as HycnButtonType } from "./components/hycn-button"
import type { Type as HycnCardType } from "./components/hycn-card"
import type { Type as HycnCarouselType } from "./components/hycn-carousel"
import type { Type as HycnCheckboxType } from "./components/hycn-checkbox"
import type { Type as HycnComboboxType } from "./components/hycn-combobox"
import type { Type as HycnDatePickerType } from "./components/hycn-date-picker"
import type { Type as HycnDialogType } from "./components/hycn-dialog"
import type { Type as HycnDisclosureType } from "./components/hycn-disclosure"
import type { Type as HycnFileInputType } from "./components/hycn-file-input"
import type { Type as HycnFlexType } from "./components/hycn-flex"
import type { Type as HycnIconType } from "./components/hycn-icon"
import type { Type as HycnImageType } from "./components/hycn-image"
import type { Type as HycnListType } from "./components/hycn-list"
import type { Type as HycnMenuType } from "./components/hycn-menu"
import type { Type as HycnNumberInputType } from "./components/hycn-number-input"
import type { Type as HycnPopoverType } from "./components/hycn-popover"
import type { Type as HycnRadioGroupType } from "./components/hycn-radio-group"
import type { Type as HycnSelectType } from "./components/hycn-select"
import type { Type as HycnSkeletonType } from "./components/hycn-skeleton"
import type { Type as HycnSliderType } from "./components/hycn-slider"
import type { Type as HycnSwitchType } from "./components/hycn-switch"
import type { Type as HycnTableType } from "./components/hycn-table"
import type { Type as HycnTabsType } from "./components/hycn-tabs"
import type { Type as HycnTagType } from "./components/hycn-tag"
import type { Type as HycnTextInputType } from "./components/hycn-text-input"
import type { Type as HycnTextType } from "./components/hycn-text"
import type { Type as HycnToastType } from "./components/hycn-toast"
import type { Type as HycnTooltipType } from "./components/hycn-tooltip"
import type { Type as HycnTreeType } from "./components/hycn-tree"
import type { Type as HycnVisuallyHiddenType } from "./components/hycn-visually-hidden"
import type { Type as SimpleCounterType } from "./components/simple-counter"

declare global {
  interface HTMLElementTagNameMap {
    "hycn-accordion": HycnAccordionType["Element"]
    "hycn-alert": HycnAlertType["Element"]
    "hycn-avatar": HycnAvatarType["Element"]
    "hycn-badge": HycnBadgeType["Element"]
    "hycn-breadcrumb": HycnBreadcrumbType["Element"]
    "hycn-button": HycnButtonType["Element"]
    "hycn-card": HycnCardType["Element"]
    "hycn-carousel": HycnCarouselType["Element"]
    "hycn-checkbox": HycnCheckboxType["Element"]
    "hycn-combobox": HycnComboboxType["Element"]
    "hycn-date-picker": HycnDatePickerType["Element"]
    "hycn-dialog": HycnDialogType["Element"]
    "hycn-disclosure": HycnDisclosureType["Element"]
    "hycn-file-input": HycnFileInputType["Element"]
    "hycn-flex": HycnFlexType["Element"]
    "hycn-icon": HycnIconType["Element"]
    "hycn-image": HycnImageType["Element"]
    "hycn-list": HycnListType["Element"]
    "hycn-menu": HycnMenuType["Element"]
    "hycn-number-input": HycnNumberInputType["Element"]
    "hycn-popover": HycnPopoverType["Element"]
    "hycn-radio-group": HycnRadioGroupType["Element"]
    "hycn-select": HycnSelectType["Element"]
    "hycn-skeleton": HycnSkeletonType["Element"]
    "hycn-slider": HycnSliderType["Element"]
    "hycn-switch": HycnSwitchType["Element"]
    "hycn-table": HycnTableType["Element"]
    "hycn-tabs": HycnTabsType["Element"]
    "hycn-tag": HycnTagType["Element"]
    "hycn-text-input": HycnTextInputType["Element"]
    "hycn-text": HycnTextType["Element"]
    "hycn-toast": HycnToastType["Element"]
    "hycn-tooltip": HycnTooltipType["Element"]
    "hycn-tree": HycnTreeType["Element"]
    "hycn-visually-hidden": HycnVisuallyHiddenType["Element"]
    "simple-counter": SimpleCounterType["Element"]
  }

}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "hycn-accordion": React.DetailedHTMLProps<React.HTMLAttributes<HycnAccordionType["Element"]>, HycnAccordionType["Element"]> & HycnAccordionType["Definition"]
      "hycn-alert": React.DetailedHTMLProps<React.HTMLAttributes<HycnAlertType["Element"]>, HycnAlertType["Element"]> & HycnAlertType["Definition"]
      "hycn-avatar": React.DetailedHTMLProps<React.HTMLAttributes<HycnAvatarType["Element"]>, HycnAvatarType["Element"]> & HycnAvatarType["Definition"]
      "hycn-badge": React.DetailedHTMLProps<React.HTMLAttributes<HycnBadgeType["Element"]>, HycnBadgeType["Element"]> & HycnBadgeType["Definition"]
      "hycn-breadcrumb": React.DetailedHTMLProps<React.HTMLAttributes<HycnBreadcrumbType["Element"]>, HycnBreadcrumbType["Element"]> & HycnBreadcrumbType["Definition"]
      "hycn-button": React.DetailedHTMLProps<React.HTMLAttributes<HycnButtonType["Element"]>, HycnButtonType["Element"]> & HycnButtonType["Definition"]
      "hycn-card": React.DetailedHTMLProps<React.HTMLAttributes<HycnCardType["Element"]>, HycnCardType["Element"]> & HycnCardType["Definition"]
      "hycn-carousel": React.DetailedHTMLProps<React.HTMLAttributes<HycnCarouselType["Element"]>, HycnCarouselType["Element"]> & HycnCarouselType["Definition"]
      "hycn-checkbox": React.DetailedHTMLProps<React.HTMLAttributes<HycnCheckboxType["Element"]>, HycnCheckboxType["Element"]> & HycnCheckboxType["Definition"]
      "hycn-combobox": React.DetailedHTMLProps<React.HTMLAttributes<HycnComboboxType["Element"]>, HycnComboboxType["Element"]> & HycnComboboxType["Definition"]
      "hycn-date-picker": React.DetailedHTMLProps<React.HTMLAttributes<HycnDatePickerType["Element"]>, HycnDatePickerType["Element"]> & HycnDatePickerType["Definition"]
      "hycn-dialog": React.DetailedHTMLProps<React.HTMLAttributes<HycnDialogType["Element"]>, HycnDialogType["Element"]> & HycnDialogType["Definition"]
      "hycn-disclosure": React.DetailedHTMLProps<React.HTMLAttributes<HycnDisclosureType["Element"]>, HycnDisclosureType["Element"]> & HycnDisclosureType["Definition"]
      "hycn-file-input": React.DetailedHTMLProps<React.HTMLAttributes<HycnFileInputType["Element"]>, HycnFileInputType["Element"]> & HycnFileInputType["Definition"]
      "hycn-flex": React.DetailedHTMLProps<React.HTMLAttributes<HycnFlexType["Element"]>, HycnFlexType["Element"]> & HycnFlexType["Definition"]
      "hycn-icon": React.DetailedHTMLProps<React.HTMLAttributes<HycnIconType["Element"]>, HycnIconType["Element"]> & HycnIconType["Definition"]
      "hycn-image": React.DetailedHTMLProps<React.HTMLAttributes<HycnImageType["Element"]>, HycnImageType["Element"]> & HycnImageType["Definition"]
      "hycn-list": React.DetailedHTMLProps<React.HTMLAttributes<HycnListType["Element"]>, HycnListType["Element"]> & HycnListType["Definition"]
      "hycn-menu": React.DetailedHTMLProps<React.HTMLAttributes<HycnMenuType["Element"]>, HycnMenuType["Element"]> & HycnMenuType["Definition"]
      "hycn-number-input": React.DetailedHTMLProps<React.HTMLAttributes<HycnNumberInputType["Element"]>, HycnNumberInputType["Element"]> & HycnNumberInputType["Definition"]
      "hycn-popover": React.DetailedHTMLProps<React.HTMLAttributes<HycnPopoverType["Element"]>, HycnPopoverType["Element"]> & HycnPopoverType["Definition"]
      "hycn-radio-group": React.DetailedHTMLProps<React.HTMLAttributes<HycnRadioGroupType["Element"]>, HycnRadioGroupType["Element"]> & HycnRadioGroupType["Definition"]
      "hycn-select": React.DetailedHTMLProps<React.HTMLAttributes<HycnSelectType["Element"]>, HycnSelectType["Element"]> & HycnSelectType["Definition"]
      "hycn-skeleton": React.DetailedHTMLProps<React.HTMLAttributes<HycnSkeletonType["Element"]>, HycnSkeletonType["Element"]> & HycnSkeletonType["Definition"]
      "hycn-slider": React.DetailedHTMLProps<React.HTMLAttributes<HycnSliderType["Element"]>, HycnSliderType["Element"]> & HycnSliderType["Definition"]
      "hycn-switch": React.DetailedHTMLProps<React.HTMLAttributes<HycnSwitchType["Element"]>, HycnSwitchType["Element"]> & HycnSwitchType["Definition"]
      "hycn-table": React.DetailedHTMLProps<React.HTMLAttributes<HycnTableType["Element"]>, HycnTableType["Element"]> & HycnTableType["Definition"]
      "hycn-tabs": React.DetailedHTMLProps<React.HTMLAttributes<HycnTabsType["Element"]>, HycnTabsType["Element"]> & HycnTabsType["Definition"]
      "hycn-tag": React.DetailedHTMLProps<React.HTMLAttributes<HycnTagType["Element"]>, HycnTagType["Element"]> & HycnTagType["Definition"]
      "hycn-text-input": React.DetailedHTMLProps<React.HTMLAttributes<HycnTextInputType["Element"]>, HycnTextInputType["Element"]> & HycnTextInputType["Definition"]
      "hycn-text": React.DetailedHTMLProps<React.HTMLAttributes<HycnTextType["Element"]>, HycnTextType["Element"]> & HycnTextType["Definition"]
      "hycn-toast": React.DetailedHTMLProps<React.HTMLAttributes<HycnToastType["Element"]>, HycnToastType["Element"]> & HycnToastType["Definition"]
      "hycn-tooltip": React.DetailedHTMLProps<React.HTMLAttributes<HycnTooltipType["Element"]>, HycnTooltipType["Element"]> & HycnTooltipType["Definition"]
      "hycn-tree": React.DetailedHTMLProps<React.HTMLAttributes<HycnTreeType["Element"]>, HycnTreeType["Element"]> & HycnTreeType["Definition"]
      "hycn-visually-hidden": React.DetailedHTMLProps<React.HTMLAttributes<HycnVisuallyHiddenType["Element"]>, HycnVisuallyHiddenType["Element"]> & HycnVisuallyHiddenType["Definition"]
      "simple-counter": React.DetailedHTMLProps<React.HTMLAttributes<SimpleCounterType["Element"]>, SimpleCounterType["Element"]> & SimpleCounterType["Definition"]
    }
  }
}
