// AUTOGENERATED - DO NOT EDIT
import type * as React from "react"
import type { Type as HycnComboboxType } from "./components/hycn-combobox"
import type { Type as HycnDialogType } from "./components/hycn-dialog"
import type { Type as HycnMenuType } from "./components/hycn-menu"
import type { Type as HycnTabsType } from "./components/hycn-tabs"
import type { Type as HycnTreeType } from "./components/hycn-tree"
import type { Type as HycnVisuallyHiddenType } from "./components/hycn-visually-hidden"
import type { Type as SimpleCounterType } from "./components/simple-counter"

declare global {
  interface HTMLElementTagNameMap {
    "hycn-combobox": HycnComboboxType["Element"]
    "hycn-dialog": HycnDialogType["Element"]
    "hycn-menu": HycnMenuType["Element"]
    "hycn-tabs": HycnTabsType["Element"]
    "hycn-tree": HycnTreeType["Element"]
    "hycn-visually-hidden": HycnVisuallyHiddenType["Element"]
    "simple-counter": SimpleCounterType["Element"]
  }

}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "hycn-combobox": React.DetailedHTMLProps<React.HTMLAttributes<HycnComboboxType["Element"]>, HycnComboboxType["Element"]> & HycnComboboxType["Definition"]
      "hycn-dialog": React.DetailedHTMLProps<React.HTMLAttributes<HycnDialogType["Element"]>, HycnDialogType["Element"]> & HycnDialogType["Definition"]
      "hycn-menu": React.DetailedHTMLProps<React.HTMLAttributes<HycnMenuType["Element"]>, HycnMenuType["Element"]> & HycnMenuType["Definition"]
      "hycn-tabs": React.DetailedHTMLProps<React.HTMLAttributes<HycnTabsType["Element"]>, HycnTabsType["Element"]> & HycnTabsType["Definition"]
      "hycn-tree": React.DetailedHTMLProps<React.HTMLAttributes<HycnTreeType["Element"]>, HycnTreeType["Element"]> & HycnTreeType["Definition"]
      "hycn-visually-hidden": React.DetailedHTMLProps<React.HTMLAttributes<HycnVisuallyHiddenType["Element"]>, HycnVisuallyHiddenType["Element"]> & HycnVisuallyHiddenType["Definition"]
      "simple-counter": React.DetailedHTMLProps<React.HTMLAttributes<SimpleCounterType["Element"]>, SimpleCounterType["Element"]> & SimpleCounterType["Definition"]
    }
  }
}

export {}
